name: PR Quality Checks
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Download Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21.x'
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Verify dependencies
        run: go mod verify
      - name: Build
        run: go build ./...
      - name: Run tests
        run: go test -v ./...
